language: go
go:
  - 1.10.x
before_install:
  - go get golang.org/x/tools/cmd/cover golang.org/x/lint/golint
  - >
    ver=2.2.3 &&
    wget -nv https://archive.apache.org/dist/hbase/$ver/hbase-$ver-bin.tar.gz &&
    echo "99F7631C9B09ED2CA4292613207F6F74B24905ED1F1146433CCA81FF88F741648A1C796D81A1A55F2166B56030D21624FC510CFA71FD9BEE3A0D5B1D5E941A5A  hbase-$ver-bin.tar.gz" | sha512sum --strict --check - &&
    tar zxf hbase-$ver-bin.tar.gz --exclude=docs &&
    ln -s hbase-$ver hbase
install:
  - ./install_ci.sh
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
before_script:
  - hbase/bin/hbase-daemon.sh --config hbase/conf start master
script:
  - make -j4 jenkins GOTEST_FLAGS=-v
